spring:
  application:
    name: checkinx-demo
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: postgres
    hikari:
      connectionTestQuery: SELECT 1
      validationTimeout: 3500
      minimumIdle: 0
      maxLifetime: 1200000
      idleTimeout: 13000
      maximumPoolSize: 15
      connectionTimeout: 20000
      driver-class-name: org.postgresql.Driver
    logging:
      enable: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    locations: classpath:db/migration